version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root

  ApplicationStart:
    - location: scripts/start_server
      runas: root
