version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.5
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Zipping app for EB deployment..."
      - zip -r eb-app.zip * .[^.]*

artifacts:
  files:
    - eb-app.zip
